[project]
name = "genesis-core"
version = "0.1.0"
description = "Your journal, only yours."
readme = "README.md"
authors = [{ name = "Chris1320", email = "me@chrisfromnowhere.me" }]
requires-python = ">=3.14"
dependencies = ["fastapi[standard]>=0.141.1"]

[project.scripts]
genesis-core = "genesis_core:main"

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx2>=2.9.1",
    "pytest>=9.1.1",
]
